make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C /srv/ilab-builds/workspace/git/RIOT/tests/xtimer_reset test
r
/srv/ilab-builds/workspace/git/RIOT/dist/tools/pyterm/pyterm -p "/dev/riot/tty-mulle" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line
Twisted not available, please install it if you want to use pyterm's JSON capabilities
Connect to serial port /dev/riot/tty-mulle
could not open port /dev/riot/tty-mulle: [Errno 2] No such file or directory: '/dev/riot/tty-mulle'
/srv/ilab-builds/workspace/git/RIOT/Makefile.include:688: recipe for target 'cleanterm' failed
make[1]: *** [cleanterm] Error 2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 150, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 465, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 155, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/ilab-builds/workspace/git/RIOT/tests/xtimer_reset/tests/01-run.py", line 24, in <module>
    sys.exit(run(testfunc))
  File "/srv/ilab-builds/workspace/git/RIOT/dist/pythonlibs/testrunner/__init__.py", line 28, in run
    logfile=sys.stdout if echo else None)
  File "/srv/ilab-builds/workspace/git/RIOT/dist/pythonlibs/testrunner/spawn.py", line 86, in setup_child
    sync_child(child, env)
  File "/srv/ilab-builds/workspace/git/RIOT/dist/pythonlibs/testrunner/spawn.py", line 117, in sync_child
    TEST_INTERACTIVE_DELAY)
  File "/srv/ilab-builds/workspace/git/RIOT/dist/pythonlibs/testrunner/utils.py", line 30, in test_utils_interactive_sync
    _test_utils_interactive_sync(child, retries, delay)
  File "/srv/ilab-builds/workspace/git/RIOT/dist/pythonlibs/testrunner/utils.py", line 17, in _test_utils_interactive_sync
    ret = child.expect_exact([ready_exp, pexpect.TIMEOUT], timeout=delay)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f37af0fa5c0>
command: /usr/bin/make
args: [b'/usr/bin/make', b'cleanterm']
buffer (last 100 chars): ''
before (last 100 chars): "/RIOT/Makefile.include:688: recipe for target 'cleanterm' failed\r\nmake[1]: *** [cleanterm] Error 2\r\n"
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 2
flag_eof: True
pid: 6650
child_fd: 5
closed: False
timeout: 10
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "READY"
    1: TIMEOUT
/srv/ilab-builds/workspace/git/RIOT/tests/xtimer_reset/../../Makefile.include:733: recipe for target 'test' failed
make: *** [test] Error 1

Return value: 2
